// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdbrtmheqsgdhzeclnwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkYnJ0bWhlcXNnZGh6ZWNsbndwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNjQyOTYsImV4cCI6MjA1NTc0MDI5Nn0.ETGkmQflncL3EofMS2shIkJsRw2KAqd7eDEEvwomzC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);